### ISSUE TITLE
semantic segment train error: Cannot find field 'gt_boxes' in the given Instances! 

### ISSUE THREAD

**Issue by hjZhouGitHub** [IDEA-Research/MaskDINO#18]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 395, in run_step
    loss_dict = self.model(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk/local_ssd1/zhj/segment/MaskDINO/maskdino/maskdino.py", line 262, in forward
    targets = self.prepare_targets(gt_instances, images)
  File "/disk/local_ssd1/zhj/segment/MaskDINO/maskdino/maskdino.py", line 350, in prepare_targets
    "boxes":box_ops.box_xyxy_to_cxcywh(targets_per_image.gt_boxes.tensor)/image_size_xyxy
  File "/opt/conda/lib/python3.7/site-packages/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'gt_boxes' in the given Instances!

Base-ADE20K-SemanticSegmentation.yaml
default set DATASET_MAPPER_NAME: "mask_former_semantic"
in MaskFormerSemanticDatasetMapper
![image](https://user-images.githubusercontent.com/49541471/205871673-65416851-3ab6-46a3-9d27-b8f1ec9aa57c.png)

input sample:
'instances': Instances(num_instances=2, image_height=640, image_width=640, fields=[gt_classes: tensor([16, 17]), gt_masks: tensor([[]])  has no "gt_bboxes"
but in maskdino.py 259:
function self.prepare_targets need a "gt_bboxes" tensor

so:
modify maskdino.py 347:
 "boxes":box_ops.box_xyxy_to_cxcywh(targets_per_image.gt_boxes.tensor)/image_size_xyxy -->  "boxes": None
or other resolvent？

Look forward to your reply, thank you！

**Comment by FengLi-ust** [comment]
Thanks for pointing out this problem. I forgot to add `gt_boxes` to semantic dataset mappers after organizing the code. I have updated the code to fix this problem.
