### ISSUE TITLE
when import libraries, already registered error is occurred.

### ISSUE THREAD

**Issue by despild** [IDEA-Research/MaskDINO#26]
First of all, thank you for sharing your works.

I try to evaluate the model for testing my environment and model with following code
`python3 train_net.py --eval-only --num-gpus 1 --config-file configs/coco/panoptic-segmentation/maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml MODEL.WEIGHTS ckpts/maskdino_r50_50ep_300q_hid2048_3sd1_panoptic_pq53.0.pth`

But, error with `AssertionError: An object named 'MaskDINOEncoder' was already registered in 'SEM_SEG_HEADS' registry!` message.

Did anyone face the same case and have a solution?

Full Error message is below. Thank you.
`Traceback (most recent call last):
  File "train_net.py", line 46, in <module>
    from maskdino import (
  File "/workspace/MaskDINO/maskdino/__init__.py", line 23, in <module>
    from .maskdino import MaskDINO
  File "/workspace/MaskDINO/maskdino/maskdino/__init__.py", line 3, in <module>
    from . import modeling
  File "/workspace/MaskDINO/maskdino/maskdino/modeling/__init__.py", line 3, in <module>
    from .pixel_decoder.maskdino_encoder import MaskDINOEncoder
  File "/workspace/MaskDINO/maskdino/maskdino/modeling/pixel_decoder/maskdino_encoder.py", line 189, in <module>
    class MaskDINOEncoder(nn.Module):
  File "/usr/local/lib/python3.8/dist-packages/fvcore/common/registry.py", line 59, in deco
    self._do_register(name, func_or_class)
  File "/usr/local/lib/python3.8/dist-packages/fvcore/common/registry.py", line 43, in _do_register
    assert (
AssertionError: An object named 'MaskDINOEncoder' was already registered in 'SEM_SEG_HEADS' registry!`

**Comment by FengLi-ust** [comment]
No sure why this is happening. You can try cloning a clean copy of our code and rerun it.

**Comment by despild** [comment]
I did get new clone repository before, and same result was appeared.
BUT after your reply, It works good. I don't know why.
Thank you for answering :)
