### ISSUE TITLE
Try to train custom panoptic cocodata and Get KeyError with "stuff_dataset_id_to_contiguous_id"

### ISSUE THREAD

**Issue by despild** [IDEA-Research/MaskDINO#40]
Thank you for your great works.

After check the train with coco2017 dataset works well,
I try to train custom panoptic cocodata. 
I made custom dataset and make simbolic link as coco dataset.

But, it makes error with follow message.

Traceback (most recent call last):
  File "train_net.py", line 380, in <module>
    launch(
  File "/usr/local/lib/python3.8/dist-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 364, in main
    trainer = Trainer(cfg)
  File "train_net.py", line 83, in __init__
    data_loader = self.build_train_loader(cfg)
  File "train_net.py", line 221, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/build.py", line 344, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/datasets/coco_panoptic.py", line 88, in <lambda>
    lambda: load_coco_panoptic_json(panoptic_json, image_root, panoptic_root, metadata),
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/datasets/coco_panoptic.py", line 51, in load_coco_panoptic_json
    segments_info = [_convert_category_id(x, meta) for x in ann["segments_info"]]
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/datasets/coco_panoptic.py", line 51, in <listcomp>
    segments_info = [_convert_category_id(x, meta) for x in ann["segments_info"]]
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/datasets/coco_panoptic.py", line 33, in _convert_category_id
    segment_info["category_id"] = meta["stuff_dataset_id_to_contiguous_id"][
KeyError: 12

I can't find the fixing point. 
Please somebody help me.

Thank you

**Comment by despild** [comment]
I solve the problem. 
I made custom dataset, but not registered on detectron2.
So, before run main functon, I do follow codes.

from detectron2.data.datasets import register_coco_instances
register_coco_instances("dataset name","annotation json file path","masked image directory path") # for train
register_coco_instances("dataset name","annotation json file path","masked image directory path") # for validation

And no more showing previous errors.

**Comment by despild** [comment]
for panoptic, need to use "register_coco_panoptic" instead of "register_coco_instances"
