### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by LiWentomng** [IDEA-Research/MaskDINO#45]
Hello, thanks for your great work.

When I run the codes, I encounter the following errors.
Can you provide any helpfully suggestions? Thanks a lot  in advance.

```
[01/26 23:47:40 d2.engine.train_loop]: Starting training from iteration 0
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
ERROR [01/26 23:47:45 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/16T-2/zitong/code/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/16T-2/zitong/code/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/16T-2/zitong/code/detectron2/detectron2/engine/train_loop.py", line 421, in run_step
    with autocast(dtype=self.precision):
TypeError: __init__() got an unexpected keyword argument 'dtype'
[01/26 23:47:45 d2.engine.hooks]: Total training time: 0:00:05 (0:00:00 on hooks)
[01/26 23:47:45 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 411M
Traceback (most recent call last):
  File "train_net.py", line 377, in <module>
    launch(
  File "/16T-2/zitong/code/detectron2/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/home/zoloz/.conda/envs/maskdino/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/16T-2/zitong/code/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/16T-2/zitong/code/MaskDINO/train_net.py", line 364, in main
    return trainer.train()
  File "/16T-2/zitong/code/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/16T-2/zitong/code/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/16T-2/zitong/code/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/16T-2/zitong/code/detectron2/detectron2/engine/train_loop.py", line 421, in run_step
    with autocast(dtype=self.precision):
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

**Comment by LiWentomng** [comment]
Is this error about the version of `detectron2` ?

**Comment by AINeurosurgery** [comment]
Hey there 
We are also facing the same issue
Please let us know how you resolve it.

Waiting for your reply
Thank you

**Comment by TyrionChou** [comment]
how to solve it?

**Comment by TyrionChou** [comment]
> how to solve it?

cause the annotation data type problem

**Comment by LiWentomng** [comment]
@TyrionChou @AINeurosurgery 
This problem is due to the compatibility of detectron2 version.
Please ckeck this [installation](https://detectron2.readthedocs.io/en/latest/tutorials/install.html) with the matching command (matching CUDA and torch version).

**Comment by ParkerLyu01** [comment]
@LiWentomng @TyrionChou @AINeurosurgery 
I think I've found the reason.
The params of class autocast of torch_1.10 looks like this: "torch.autocast(device_type, enabled=True, **kwargs)", it do not acccept a param named "dtype". You can check it from [here](https://pytorch.org/docs/1.10/amp.html?highlight=autocast#)

So, the solution:
1、 change default parameters of class AMPTrainer(SimpleTrainer): The value of precision need to be True;
2、change the usage method， the right format is : "with autocast(self.precision):"
