### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get_bounding_boxes'

### ISSUE THREAD

**Issue by otakutyrant** [IDEA-Research/MaskDINO#51]
I try to train `maskdino_r50_50ep_100q_celoss_hid1024_3s_semantic_cityscapes_79.8miou.pth` with this config `[MaskDINO](https://github.com/IDEA-Research/MaskDINO)/[configs](https://github.com/IDEA-Research/MaskDINO/tree/main/configs)/[cityscapes](https://github.com/IDEA-Research/MaskDINO/tree/main/configs/cityscapes)/[semantic-segmentation](https://github.com/IDEA-Research/MaskDINO/tree/main/configs/cityscapes/semantic-segmentation)/maskdino_R50_bs16_90k_steplr.yaml`. The command is `python train_net.py --num-gpus 1 --config-file configs/cityscapes/semantic-segmentation/maskdino_R50_bs16_90k_steplr.yaml  MODEL.WEIGHTS maskdino_r50_50ep_100q_celoss_hid1024_3s_semantic_cityscapes_79.8miou.pth`

The error log is:

```
2
11
2
13
11
12
4
1
12
12
11
2
0
11
4
12
11
5
12
[02/14 20:40:13 d2.utils.events]:  eta: 14:30:56  iter: 419  total_loss: 79.05  loss_ce: 0.7662  loss_mask: 0.4672  loss_dice: 1.376  loss_bbox: 0.641  loss_giou: 0.7265  loss_ce_dn: 0.3494  loss_mask_dn: 0.5014  loss_dice_dn: 1.254  loss_bbox_dn: 0.2784  loss_giou_dn: 0.3464  loss_ce_0: 1.648  loss_mask_0: 0.4273  loss_dice_0: 1.536  loss_bbox_0: 3.453  loss_giou_0: 1.724  loss_ce_1: 1.129  loss_mask_1: 0.4599  loss_dice_1: 1.435  loss_bbox_1: 1.292  loss_giou_1: 1.109  loss_ce_dn_1: 0.8849  loss_mask_dn_1: 0.5496  loss_dice_dn_1: 1.32  loss_bbox_dn_1: 0.4981  loss_giou_dn_1: 0.4988  loss_ce_2: 0.9948  loss_mask_2: 0.4748  loss_dice_2: 1.334  loss_bbox_2: 0.9305  loss_giou_2: 0.9705  loss_ce_dn_2: 0.399  loss_mask_dn_2: 0.5417  loss_dice_dn_2: 1.294  loss_bbox_dn_2: 0.3806  loss_giou_dn_2: 0.4247  loss_ce_3: 0.7965  loss_mask_3: 0.4374  loss_dice_3: 1.374  loss_bbox_3: 0.7992  loss_giou_3: 0.8476  loss_ce_dn_3: 0.2176  loss_mask_dn_3: 0.5195  loss_dice_dn_3: 1.283  loss_bbox_dn_3: 0.3308  loss_giou_dn_3: 0.3852  loss_ce_4: 0.7999  loss_mask_4: 0.4505  loss_dice_4: 1.355  loss_bbox_4: 0.7958  loss_giou_4: 0.8001  loss_ce_dn_4: 0.2266  loss_mask_dn_4: 0.5241  loss_dice_dn_4: 1.261  loss_bbox_dn_4: 0.3066  loss_giou_dn_4: 0.3541  loss_ce_5: 0.9027  loss_mask_5: 0.4278  loss_dice_5: 1.316  loss_bbox_5: 0.6092  loss_giou_5: 0.8138  loss_ce_dn_5: 0.1839  loss_mask_dn_5: 0.5166  loss_dice_dn_5: 1.279  loss_bbox_dn_5: 0.2979  loss_giou_dn_5: 0.3484  loss_ce_6: 0.6809  loss_mask_6: 0.4294  loss_dice_6: 1.335  loss_bbox_6: 0.6096  loss_giou_6: 0.7339  loss_ce_dn_6: 0.2392  loss_mask_dn_6: 0.526  loss_dice_dn_6: 1.29  loss_bbox_dn_6: 0.2936  loss_giou_dn_6: 0.3468  loss_ce_7: 0.7687  loss_mask_7: 0.4149  loss_dice_7: 1.362  loss_bbox_7: 0.624  loss_giou_7: 0.7326  loss_ce_dn_7: 0.2941  loss_mask_dn_7: 0.5212  loss_dice_dn_7: 1.293  loss_bbox_dn_7: 0.2868  loss_giou_dn_7: 0.3471  loss_ce_8: 0.7624  loss_mask_8: 0.456  loss_dice_8: 1.393  loss_bbox_8: 0.6341  loss_giou_8: 0.7605  loss_ce_dn_8: 0.3587  loss_mask_dn_8: 0.5122  loss_dice_dn_8: 1.299  loss_bbox_dn_8: 0.281  loss_giou_dn_8: 0.3456  time: 0.5916  data_time: 0.0030  lr: 0.0001  max_mem: 3626M
ERROR [02/14 20:40:13 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 268, in run_step
    data = next(self._data_loader_iter)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 291, in __iter__
    for d in self.dataset:
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 258, in __iter__
    yield self.dataset[idx]
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 95, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/otakutyrant/Projects/MaskDINO/maskdino/data/dataset_mappers/mask_former_semantic_dataset_mapper.py", line 182, in __call__
    instances.gt_boxes = masks.get_bounding_boxes()
AttributeError: 'list' object has no attribute 'get_bounding_boxes'

[02/14 20:40:13 d2.engine.hooks]: Overall training speed: 418 iterations in 0:04:07 (0.5917 s / it)
[02/14 20:40:13 d2.engine.hooks]: Total training time: 0:04:08 (0:00:01 on hooks)
[02/14 20:40:13 d2.utils.events]:  eta: 14:30:55  iter: 420  total_loss: 79.05  loss_ce: 0.7662  loss_mask: 0.4672  loss_dice: 1.376  loss_bbox: 0.641  loss_giou: 0.7265  loss_ce_dn: 0.3494  loss_mask_dn: 0.5014  loss_dice_dn: 1.254  loss_bbox_dn: 0.2784  loss_giou_dn: 0.3464  loss_ce_0: 1.648  loss_mask_0: 0.4273  loss_dice_0: 1.536  loss_bbox_0: 3.453  loss_giou_0: 1.724  loss_ce_1: 1.129  loss_mask_1: 0.4599  loss_dice_1: 1.435  loss_bbox_1: 1.292  loss_giou_1: 1.109  loss_ce_dn_1: 0.8849  loss_mask_dn_1: 0.5496  loss_dice_dn_1: 1.32  loss_bbox_dn_1: 0.4981  loss_giou_dn_1: 0.4988  loss_ce_2: 0.9948  loss_mask_2: 0.4748  loss_dice_2: 1.334  loss_bbox_2: 0.9305  loss_giou_2: 0.9705  loss_ce_dn_2: 0.399  loss_mask_dn_2: 0.5417  loss_dice_dn_2: 1.294  loss_bbox_dn_2: 0.3806  loss_giou_dn_2: 0.4247  loss_ce_3: 0.7965  loss_mask_3: 0.4374  loss_dice_3: 1.374  loss_bbox_3: 0.7992  loss_giou_3: 0.8476  loss_ce_dn_3: 0.2176  loss_mask_dn_3: 0.5195  loss_dice_dn_3: 1.283  loss_bbox_dn_3: 0.3308  loss_giou_dn_3: 0.3852  loss_ce_4: 0.7999  loss_mask_4: 0.4505  loss_dice_4: 1.355  loss_bbox_4: 0.7958  loss_giou_4: 0.8001  loss_ce_dn_4: 0.2266  loss_mask_dn_4: 0.5241  loss_dice_dn_4: 1.261  loss_bbox_dn_4: 0.3066  loss_giou_dn_4: 0.3541  loss_ce_5: 0.9027  loss_mask_5: 0.4278  loss_dice_5: 1.316  loss_bbox_5: 0.6092  loss_giou_5: 0.8138  loss_ce_dn_5: 0.1839  loss_mask_dn_5: 0.5166  loss_dice_dn_5: 1.279  loss_bbox_dn_5: 0.2979  loss_giou_dn_5: 0.3484  loss_ce_6: 0.6809  loss_mask_6: 0.4294  loss_dice_6: 1.335  loss_bbox_6: 0.6096  loss_giou_6: 0.7339  loss_ce_dn_6: 0.2392  loss_mask_dn_6: 0.526  loss_dice_dn_6: 1.29  loss_bbox_dn_6: 0.2936  loss_giou_dn_6: 0.3468  loss_ce_7: 0.7687  loss_mask_7: 0.4149  loss_dice_7: 1.362  loss_bbox_7: 0.624  loss_giou_7: 0.7326  loss_ce_dn_7: 0.2941  loss_mask_dn_7: 0.5212  loss_dice_dn_7: 1.293  loss_bbox_dn_7: 0.2868  loss_giou_dn_7: 0.3471  loss_ce_8: 0.7624  loss_mask_8: 0.456  loss_dice_8: 1.393  loss_bbox_8: 0.6341  loss_giou_8: 0.7605  loss_ce_dn_8: 0.3587  loss_mask_dn_8: 0.5122  loss_dice_dn_8: 1.299  loss_bbox_dn_8: 0.281  loss_giou_dn_8: 0.3456  time: 0.591
6  data_time: 0.0030  lr: 0.0001  max_mem: 3626M
Traceback (most recent call last):
  File "/home/otakutyrant/Projects/MaskDINO/train_net.py", line 388, in <module>
    launch(
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/home/otakutyrant/Projects/MaskDINO/train_net.py", line 375, in main
    return trainer.train()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 268, in run_step
    data = next(self._data_loader_iter)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 291, in __iter__
    for d in self.dataset:
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 258, in __iter__
    yield self.dataset[idx]
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/data/common.py", line 95, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/otakutyrant/Projects/MaskDINO/.env/lib/python3.10/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/otakutyrant/Projects/MaskDINO/maskdino/data/dataset_mappers/mask_former_semantic_dataset_mapper.py", line 182, in __call__
    instances.gt_boxes = masks.get_bounding_boxes()
AttributeError: 'list' object has no attribute 'get_bounding_boxes'
```

Those number lines are printed by `print(len(masks))` before `instances.gt_boxes = masks.get_bounding_boxes()`.

**Comment by huxycn** [comment]
![image](https://user-images.githubusercontent.com/49256066/220624108-76136f4f-5e09-499d-9fbc-a9c97d9df0f2.png)

**Comment by otakutyrant** [comment]
This fix seems okay. Time to update the code.
